name: levelus
services:
  levelus-frontend:
    container_name: levelus-frontend
    image: ghcr.io/fyrlex/levelus:frontend
    environment:
      NODE_ENV: production
    ports:
      - 127.0.0.1:8001:8001
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
  levelus-backend:
    container_name: levelus-backend
    image: ghcr.io/fyrlex/levelus:backend
    env_file: ./backend/.env
    ports:
      - 127.0.0.1:8000:8000
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    restart: unless-stopped
